steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['auth', 'configure-docker']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/crypto-volume-change-tracker:$SHORT_SHA'
      - '.'

  # Step 2: Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'crypto-volume-tracker'
      - '--image'
      - 'gcr.io/$PROJECT_ID/crypto-volume-change-tracker:$SHORT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

  # Step 3: Set the IAM policy to allow public access (if required)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'beta'
      - 'run'
      - 'services'
      - 'add-iam-policy-binding'
      - '--region=us-central1'
      - '--member=allUsers'
      - '--role=roles/run.invoker'
      - 'crypto-volume-tracker'

images:
  - 'gcr.io/$PROJECT_ID/crypto-volume-change-tracker:$SHORT_SHA'
