steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/crypto-volume-change-tracker:$SHORT_SHA'
      - '.'

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/crypto-volume-change-tracker:$SHORT_SHA'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'crypto-volume-tracker'
      - '--image'
      - 'gcr.io/$PROJECT_ID/crypto-volume-change-tracker:$SHORT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

  # Step 4: Set the IAM policy to allow public access
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'services'
      - 'add-iam-policy-binding'
      - 'crypto-volume-tracker'
      - '--region=us-central1'
      - '--member=allUsers'
      - '--role=roles/run.invoker'

images:
  - 'gcr.io/$PROJECT_ID/crypto-volume-change-tracker:$SHORT_SHA'

logsBucket: gs://crypto-backend-log-bucket