steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['auth', 'configure-docker']

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/crypto-volume-tracker:$SHORT_SHA'
  - '.'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'crypto-volume-tracker'
  - '--image'
  - 'gcr.io/$PROJECT_ID/crypto-volume-tracker:$SHORT_SHA'
  - '--platform'
  - 'managed'
  - '--region'
  - 'us-central1'
  - '--allow-unauthenticated'

images:
- 'gcr.io/$PROJECT_ID/crypto-volume-tracker:$SHORT_SHA'

options:
  logging: NONE
